#!/bin/bash

cd /home/ryan/code/renderer-code

rm -rf ./build
mkdir ./build
cd build

/opt/clion/clion-2024.2.1/bin/cmake/linux/x64/bin/cmake ..
/opt/clion/clion-2024.2.1/bin/cmake/linux/x64/bin/cmake --build .

sudo make install
